apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-blue
  namespace: skillify
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
      version: blue
  template:
    metadata:
      labels:
        app: backend
        version: blue
    spec:
      containers:
        - name: backend
          image: nigachu42/backend:latest
          ports:
            - containerPort: 5000
