apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-green
  namespace: skillify
spec:
  replicas: 2
  selector:
    matchLabels:
      app: frontend
      version: green
  template:
    metadata:
      labels:
        app: frontend
        version: green
    spec:
      containers:
        - name: frontend
          image: nigachu42/frontend:latest
          ports:
            - containerPort: 80
