apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: skillify
spec:
  selector:
    app: backend
    version: blue
  ports:
    - port: 5000
      targetPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: skillify
spec:
  selector:
    app: frontend
    version: blue
  ports:
    - port: 80
      targetPort: 80