apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-canary
  namespace: skillify
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
      track: canary
  template:
    metadata:
      labels:
        app: backend
        track: canary
    spec:
      containers:
        - name: backend
          image: nigachu42/backend:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 5000
